# Generated by Django 4.2.2 on 2023-06-20 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0002_alter_branch_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=120)),
                ('patronymic', models.CharField(max_length=120)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=8)),
                ('emp_number', models.CharField(max_length=30)),
                ('working_since', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('mail', models.EmailField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='workers_photo/')),
                ('three_gen', models.FileField(blank=True, null=True, upload_to='workers_three_gen/')),
                ('employment_history', models.FileField(blank=True, null=True, upload_to='workers_employment_history/')),
                ('passport_copy', models.FileField(blank=True, null=True, upload_to='workers_passport_copy/')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='branch.branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='branch.department')),
            ],
        ),
    ]
