# Generated by Django 4.2.2 on 2023-07-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_alter_worker_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='name',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='surname',
        ),
        migrations.AddField(
            model_name='worker',
            name='fullname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
